# Uncomment the next line to define a global platform for your project
# platform :ios, '15'

target 'CaveTickers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CaveTickers
    pod 'Charts'
    pod 'SwiftLint'

end


